import type { Metadata } from "next";
import { Inter, Work_Sans } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/layouts/header";

const inter = Inter({ subsets: ["latin"] });
const work_sans = Work_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pulse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${work_sans.className} antialiased`}>
      <body className="bg-[#eafaf1]">
        <section className="md:container mx-auto ">
          <Header />
          <main>{children}</main>
        </section>
      </body>
    </html>
  );
}
